// This is a skeleton starter React component generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";
import { PlasmicBaseCard } from "./plasmic/mysilio_plasmic_codegen_gate/PlasmicBaseCard";

function BaseCard_(props, ref) {
  // Use PlasmicBaseCard to render this component as it was
  // designed in Plasmic, by activating the appropriate variants,
  // attaching the appropriate event handlers, etc.  You
  // can also install whatever React hooks you need here to manage state or
  // fetch data.
  //
  // Props you can pass into PlasmicBaseCard are:
  // 1. Variants you want to activate,
  // 2. Contents for slots you want to fill,
  // 3. Overrides for any named node in the component to attach behavior and data,
  // 4. Props to set on the root node.
  //
  // By default, we are just piping all BaseCardProps here, but feel free
  // to do whatever works for you.
  return <PlasmicBaseCard root={{ ref }} {...props} />;
}

const BaseCard = React.forwardRef(BaseCard_);

export default BaseCard;
